<?php
	
	$lang	= array
	(
		'edtprf_ttl_info'		=> 'Редакция на профил',
		'edtprf_ttl_avatar'	=> 'Редакция на аватар',
		'edtprf_ttl_tags'		=> 'Редакция на тагове',
		'edtprf_ttl_password'	=> 'Смяна на парола',
		'edtprf_ttl_email'	=> 'Смяна на e-mail адрес',
		'edtprf_ttl_ignored'	=> 'Игнорирани потребители',
		'edtprf_ttl_notif'	=> 'Известия по e-mail',
		'edtprf_ttl_feed'	=> 'Постване от feed',
		
		'prof_tab_info'		=> 'Инфо',
		'prof_tab_avatar'		=> 'Аватар',
		'prof_tab_tags'		=> 'Тагове',
		'prof_tab_password'	=> 'Парола',
		'prof_tab_email'		=> 'E-mail',
		'prof_tab_ignored'	=> 'Ignore',
		'prof_tab_notif'		=> 'Известия',
		'prof_tab_feed'		=> 'Feed',
		
		'profinfo_fullname'	=> 'Истинско име',
		'profinfo_fullname_dsc'	=> 'Твоето истинско име',
		'profinfo_website'	=> 'Уеб сайт',
		'profinfo_website_dsc'	=> 'Личен сайт, блог или профил',
		'profinfo_website_err'	=> 'Моля посочете валиден сайт',
		'profinfo_city'		=> 'Населено място',
		'profinfo_city_dsc'	=> 'Град / село',
		'profinfo_gender'		=> 'Пол',
		'profinfo_gender_m'	=> 'мъж',
		'profinfo_gender_f'	=> 'жена',
		'profinfo_birthdt'	=> 'Рожденна дата',
		'profinfo_birthdt_dsc'	=> 'Формат: ден-месец-година',
		'profinfo_aboutme'	=> 'Няколко думи за теб',
		'profinfo_aboutme_dsc'	=> 'Кратко описание до 80 символа',
		'profinfo_tags'		=> 'Лични тагове',
		'profinfo_tags_dsc'	=> 'За да те намират по-лесно',
		'profinfo_tags_dscr'	=> 'За да те намират по-лесно:<br />Въведи до 10 тага, с които се определяш.<br />Разделяй ги със запетая.',
		'submitinfo_ok'	=> 'Готово',
		'submitinfo_ok1'	=> 'Информацията е запазена успешно.',
		'submitinfo_err'	=> 'Грешка',
		'submitinfo_err1'	=> 'Невалиден сайт',
		
		'profavat_noavat'	=> 'Все още нямаш аватар!',
		'profavat_add'	=> 'Оттук можеш да качиш',
		'profavat_avat'	=> 'Текущ аватар',
		'profavat_add2'	=> 'Качи нов аватар',
		'profavat_help'	=> 'Позволени формати: GIF/JPEG/PNG.<br />Картинката трябва да е не по-малка от '.AVATAR_SIZE.'x'.AVATAR_SIZE.' пиксела.<br />Ако формата й не е квадратна, части от нея ще бъдат изрязани.',
		'profavat_add_ok'		=> 'Готово',
		'profavat_add_ok1'	=> 'Аватарът е качен успешно',
		'profavat_add_err'	=> 'Грешка',
		'profavat_add_err1'	=> 'Посоченият файл е невалиден.',
		'profavat_add_err2'	=> 'Посочената картинка е твърде малка.',
		'profavat_add_err3'	=> 'Аватарът не може да бъде копиран.',
		
		'profmail_now'	=> 'Текущ e-mail',
		'profmail_new'	=> 'Нов e-mail адрес',
		'profmail_new_2'	=> 'Посочи новия ти e-mail адрес',
		'profmail_new2'	=> 'Въведи отново',
		'profmail_new2_2'	=> 'За потвърждение',
		'profmail_pass'	=> 'Въведи паролата си',
		'profmail_pass_2'	=> 'За потвърждение',
		'submitmail_ok'	=> 'Готово',
		'submitmail_ok1'	=> 'E-mail адресът ти беше сменен успешно.',
		'submitmail_err'	=> 'Грешка',
		'submitmail_err1'	=> 'Невалиден e-mail адрес.',
		'submitmail_err2'	=> 'E-mail адресът е същият като сегашния :)',
		'submitmail_err3'	=> 'Въведените адреси не съвпадат.',
		'submitmail_err4'	=> 'Има друг потребител с този e-mail адрес.',
		'submitmail_err5'	=> 'Въведената парола е грешна.',
		
		'profpass_now'	=> 'Текуща парола',
		'profpass_now_2'	=> 'Въведи сегашната ти парола',
		'profpass_new'	=> 'Нова парола',
		'profpass_new_2'	=> 'Въведи си новата парола',
		'profpass_new2'	=> 'Въведи отново',
		'profpass_new2_2'	=> 'За потвърждение',
		'submitpass_ok'	=> 'Готово',
		'submitpass_ok1'	=> 'Паролата ти беше сменена успешно.',
		'submitpass_err'	=> 'Грешка',
		'submitpass_err1'	=> 'Паролата трябва да е поне 5 символа.',
		'submitpass_err2'	=> 'Въведените пароли не съвпадат.',
		'submitpass_err3'	=> 'Грешна текуща парола',
		
		'edit_submit'	=> 'Запази',
		'edit_submit2'	=> 'Качи',
		
		'ignored_nores_ttl'	=> 'Няма игнорирани потребители',
		'ignored_nores_txt'	=> 'Все още не сте игнорирали никого.',
		'ignored_delete_btn'	=> 'премахни',
		'ignored_del_confirm'	=> 'Прекратяване на игнорирането - сигурни ли сте?',
		
		'notif_onwatch'	=> 'Известявай ме всеки път, когато някой започне да ме следи',
		'notif_ondirect'	=> 'Известявай ме всеки път, когато някой ми пише лично съобщение',
		'notif_onmention'	=> 'Известявай ме всеки път, когато някой ме спомене в поста си',
		'notif_periodic1'	=> 'Известявай ме',
		'notif_periodic2'	=> 'за новостите, свързани с мен и приятелите ми ',
		'notif_periodd'	=> 'веднъж на ден',
		'notif_periodm'	=> 'веднъж на седмица',
		'notif_ok_ttl'	=> 'Готово',
		'notif_ok_txt'	=> 'Информацията е запазена успешно.',
		
		'proffeed_txt'	=> 'RSS/Atom feed:',
		'proffeed_ok'	=> 'Готово',
		'proffeed_err'	=> 'Грешка',
		'proffeed_oktxt1'		=> 'Фийдът беше добавен успешно.',
		'proffeed_oktxt2'		=> 'Фийдът беше премахнат успешно.',
		'proffeed_err_invalid'	=> 'Посоченият фийд не може да бъде прочетен коректно.',
		'proffeed_submit1'	=> 'Добави',
		'proffeed_submit2'	=> 'Промени',
		
	);
	
?>
