<?php
             
              $lang              = array
              (
                            'edtprf_ttl_info'                            => 'Changer votre page de profil',
                            'edtprf_ttl_avatar'              => 'Changer votre avatar',
                            'edtprf_ttl_tags'                            => 'Changer vos étiquettes',
                            'edtprf_ttl_password'              => 'Changer votre mot de passe',
                            'edtprf_ttl_email'              => 'Changer votre adresse e-mail',
                            'edtprf_ttl_ignored'              => 'Négliger des usagers',
                            'edtprf_ttl_notif'              => 'Notifications par e-mail',
                            'edtprf_ttl_feed'              => 'Postes des Nouvelles',
                           
                            'prof_tab_info'                            => 'Info',
                            'prof_tab_avatar'                            => 'Avatar',
                            'prof_tab_tags'                            => 'Étiquettes',
                            'prof_tab_password'              => 'Mot de passe',
                            'prof_tab_email'                            => 'E-mail',
                            'prof_tab_ignored'              => 'Négliger ',
                            'prof_tab_notif'                            => 'Notifications',
                            'prof_tab_feed'                            => 'Nouvelles',
                           
                            'profinfo_fullname'              => 'Nom entier',
                            'profinfo_fullname_dsc'              => 'Remplir votre nom de famille et prénom',
                            'profinfo_website'              => 'Website Personnel ',
                            'profinfo_website_dsc'              => 'Site personnelle, blog ou profile',
                            'profinfo_website_err'              => 'Donner une site valable',
                            'profinfo_city'                            => 'Lieu',
                            'profinfo_city_dsc'              => 'Pays ou Ville',
                            'profinfo_gender'                            => 'Sexe',
                            'profinfo_gender_m'              => 'Male',
                            'profinfo_gender_f'              => 'Femelle',
                            'profinfo_birthdt'              => 'Date de naissance',
                            'profinfo_birthdt_dsc'              => 'Format: Mois-Jour-Année',
                            'profinfo_aboutme'              => 'Écivez quelque chose personnel',
                            'profinfo_aboutme_dsc'              => 'Decrciption courte, maximum de 80 symboles',
                            'profinfo_tags'                            => 'Étiquettes personnelles',
                            'profinfo_tags_dsc'              => 'Vos étiquettes personnelles',
                            'profinfo_tags_dscr'              => 'Vos étiquettes personnelles:<br />Maximum de 10 étiquettes personnelles.<br />Séparer les avec une virgule.',
                            'submitinfo_ok'              => 'Sauver',
                            'submitinfo_ok1'              => 'L\'information a été sauvé avec succès.',
                            'submitinfo_err'              => 'Erreur',
                            'submitinfo_err1'              => 'Site n\'est pas valable',
                           
                            'profavat_noavat'              => 'Vous n\'avez toujours pas d\'avatar!',
                            'profavat_add'              => 'Vous pouvez le télécharger ici',
                            'profavat_avat'              => 'Votre avatar',
                            'profavat_add2'              => 'Remplacer votre avatar',
                            'profavat_help'              => 'Formats valables: GIF/JPEG/PNG.<br />Cette photo doit être plus grand que '.AVATAR_SIZE.'x'.AVATAR_SIZE.' pixels.<br />Si la forme n\'est pas un carré, quelques parties seront coupées.',
                            'profavat_add_ok'                            => 'Fini',
                            'profavat_add_ok1'              => 'L\'avatar était téléchargé avec succès',
                            'profavat_add_err'              => 'Erreur',
                            'profavat_add_err1'              => 'Dossier indiqué n\'est pas valable.',
                            'profavat_add_err2'              => 'Phot indiquée est trop petite.',
                            'profavat_add_err3'              => 'L\'avatar ne peut pas être copiée.',
                          
                            'profmail_now'              => 'Adresse e-mail',
                            'profmail_new'              => 'Nouvelle adresse e-mail',
                            'profmail_new_2'              => 'Indiquez votre nouvelle adresse e-mail',
                            'profmail_new2'              => 'Indiquez votre nouvelle adresse e-mail encore une fois',
                            'profmail_new2_2'              => 'Pour la confirmation',
                            'profmail_pass'              => 'Votre mot de passe',
                            'profmail_pass_2'              => 'Pour votre sécurité',
                            'submitmail_ok'              => 'Fini',
                            'submitmail_ok1'              => 'Votre adresse e-mail a été changé avec succès.',
                            'submitmail_err'              => 'Erreur',
                            'submitmail_err1'              => 'L\'adresse e-mail n\'est pas valable.',
                            'submitmail_err2'              => 'L\'adresse e-mail est toujours la même que la votre maintenant :)',
                            'submitmail_err3'              => 'Les adresses e-mails ne correspondent pas.',
                            'submitmail_err4'              => 'Il y a déjà un autre usager avec le même mot de passe.',
                            'submitmail_err5'              => 'Le mot de passe est faux.',
                           
                            'profpass_now'              => 'Votre mot de passe',
                            'profpass_now_2'              => 'Taper votre mot de passe',
                            'profpass_new'              => 'Nouvelle mot de passe',
                            'profpass_new_2'              => 'Nouvelle mot de passe',
                            'profpass_new2'              => 'Nouvelle mot de passe encore',
                            'profpass_new2_2'              => 'Pour la confirmation',
                            'submitpass_ok'              => 'Fini',
                            'submitpass_ok1'              => 'Votre mot de passe a été changé avec succès.',
                            'submitpass_err'              => 'Fini',
                            'submitpass_err1'              => 'Le mot de passe doit être au moins 5 symbôles de long.',
                            'submitpass_err2'              => 'Les mots de passe ne correspondent pas.',
                            'submitpass_err3'              => 'Votre premier mot de passe est faux',
                           
                            'edit_submit'              => 'Sauver',
                            'edit_submit2'              => 'Télécharger',
                           
                            'ignored_nores_ttl'              => 'Il n\'y a pas d\'usagers négligés',
                            'ignored_nores_txt'              => 'Vous n\'avez négligé personne.',
                            'ignored_delete_btn'              => 'effacer',
                            'ignored_del_confirm'              => 'Arrêtez de négliger – Étes vous sûre?',
                           
                            'notif_onwatch'              => 'Notifier moi quand quelqu\'un est en train de me suivre',
                            'notif_ondirect'              => 'Notifier moi quand quelqu\'un m\'a envoyé un message direct',
                            'notif_onmention'              => 'Notifier moi quand quelqu\'un m\'a mentionné dans une de ses postes',
                            'notif_periodic1'              => 'Notifier moi',
                            'notif_periodic2'              => 'POur les nouvelles entourant mes amis et moi ',
                            'notif_periodd'              => 'une fois par jour',
                            'notif_periodm'              => 'une fois par semaine',
                            'notif_ok_ttl'              => 'Fini',
                            'notif_ok_txt'              => 'Information a été sauvé avec succès.',
                           
                            'proffeed_txt'              => 'RSS/Atom feed:',
                            'proffeed_ok'              => 'Fini',
                            'proffeed_err'              => 'Erreur',
                            'proffeed_oktxt1'                            => 'Les nouvelles a été ajouté avec succès.',
                            'proffeed_oktxt2'                            => 'Les nouvelles a été affacé avec succès.',
                            'proffeed_err_invalid'              => 'Les nouvelles indiquées n\'étaient pas lues correctement.',
                            'proffeed_submit1'              => 'Fini',
                            'proffeed_submit2'              => 'Change',
                           
              );
             
?>