<?php
	
	$lang	= array
	(
		'edtprf_ttl_info'		=> 'プロファールを編集',
		'edtprf_ttl_avatar'	=> 'アバターを編集',
		'edtprf_ttl_tags'		=> 'タグを編集',
		'edtprf_ttl_password'	=> 'パスワードを変更',
		'edtprf_ttl_email'	=> 'Eメールアドレスを変更',
		'edtprf_ttl_ignored'	=> '無視したユーザー',
		'edtprf_ttl_notif'	=> 'Eメールアドレスで通知',
		'edtprf_ttl_feed'	=> 'フィードからのポスト',
		
		'prof_tab_info'		=> '情報',
		'prof_tab_avatar'		=> 'アバター',
		'prof_tab_tags'		=> 'タグ',
		'prof_tab_password'	=> 'パスワード',
		'prof_tab_email'		=> 'Eメール',
		'prof_tab_ignored'	=> '無視した',
		'prof_tab_notif'		=> '通知',
		'prof_tab_feed'		=> 'フィード',
		
		'profinfo_fullname'	=> 'フルネーム',
		'profinfo_fullname_dsc'	=> 'ファーストネームと名字を入力して下さい',
		'profinfo_website'	=> '個人サイト',
		'profinfo_website_dsc'	=> '個人サイト・ブログ・プロフィール',
		'profinfo_website_err'	=> '有効なサイトのアドレスを入力して下さい',
		'profinfo_city'		=> '場所',
		'profinfo_city_dsc'	=> '国・都市',
		'profinfo_gender'		=> '性別',
		'profinfo_gender_m'	=> '男性',
		'profinfo_gender_f'	=> '女性',
		'profinfo_birthdt'	=> '誕生日',
		'profinfo_birthdt_dsc'	=> '例: 月月-日日-年年',
		'profinfo_aboutme'	=> '自分自身のことを書いて下さい',
		'profinfo_aboutme_dsc'	=> '80文字以下の叙述を書いて下さい',
		'profinfo_tags'		=> '個人なタグ',
		'profinfo_tags_dsc'	=> '個人なタグ',
		'profinfo_tags_dscr'	=> '個人なタグ:<br />自分自身を記述するために10のタグを追加します.<br />カンマで別.',
		'submitinfo_ok'	=> '保存',
		'submitinfo_ok1'	=> '情報が成功に保存されました.',
		'submitinfo_err'	=> 'エラー',
		'submitinfo_err1'	=> '無効なサイト',
		
		'profavat_noavat'	=> 'まだアバターがありません!',
		'profavat_add'	=> 'ここにアップロードして出来ます',
		'profavat_avat'	=> '現在のアバター',
		'profavat_add2'	=> 'アバターを変更',
		'profavat_help'	=> '可能な形式: GIF/JPEG/PNG.<br />写真より'.AVATAR_SIZE.'x'.AVATAR_SIZE.'を大きくする必要があります.<br />形状が、正方形じゃない場合は、その部分はカットされます.',
		'profavat_add_ok'		=> '完了',
		'profavat_add_ok1'	=> 'アバターが成功にアップロードされました',
		'profavat_add_err'	=> 'エラー',
		'profavat_add_err1'	=> '表示するフィールドが間違います.',
		'profavat_add_err2'	=> '表示する画像が小さすぎる.',
		'profavat_add_err3'	=> 'アバターをコピーすることはできません.',
		
		'profmail_now'	=> '現在のEメール',
		'profmail_new'	=> '新Eメールアドレス',
		'profmail_new_2'	=> '新Eメールアドレスを表示して下さい',
		'profmail_new2'	=> 'もう一度Eメールを入力',
		'profmail_new2_2'	=> '確認',
		'profmail_pass'	=> '現在のパスワード',
		'profmail_pass_2'	=> '安全保障のために',
		'submitmail_ok'	=> '完了',
		'submitmail_ok1'	=> 'Eメールアドレスを成功に変更されました.',
		'submitmail_err'	=> 'エラー',
		'submitmail_err1'	=> '無効なサイト.',
		'submitmail_err2'	=> '現在のEメールアドレスと同じです',
		'submitmail_err3'	=> 'Eメールは同じしゃありません.',
		'submitmail_err4'	=> '他のユーザーはこのEメールを使用しています.',
		'submitmail_err5'	=> 'パスワードが間違いました.',
		
		'profpass_now'	=> '現在のパスワード',
		'profpass_now_2'	=> '現在のパスワードを入力して下さい',
		'profpass_new'	=> '新パスワード',
		'profpass_new_2'	=> '新しいパスワードを入力して下さい',
		'profpass_new2'	=> 'まだ新しいパスワードを入力して下さい',
		'profpass_new2_2'	=> '確認',
		'submitpass_ok'	=> '完了',
		'submitpass_ok1'	=> 'パスワードを成功に変更されました.',
		'submitpass_err'	=> '完了',
		'submitpass_err1'	=> '文字以上のパスワードが必要です .',
		'submitpass_err2'	=> 'パスワードが同じじゃありません.',
		'submitpass_err3'	=> '間違う現在のパスワード',
		
		'edit_submit'	=> '保存',
		'edit_submit2'	=> 'アップロード',
		
		'ignored_nores_ttl'	=> '無視したユーザーがありません',
		'ignored_nores_txt'	=> 'まだ誰も無視しません.',
		'ignored_delete_btn'	=> '取消',
		'ignored_del_confirm'	=> '無視停止 – よろしいですか?',
		
		'notif_onwatch'	=> '通知を開始するたびに誰かに従う',
		'notif_ondirect'	=> 'たびに誰かに直接メッセージを送る通知',
		'notif_onmention'	=> 'たびに誰か私に言及する通知',
		'notif_periodic1'	=> '私に通知',
		'notif_periodic2'	=> '私と私の友達についてニュース',
		'notif_periodd'	=> '1日1回',
		'notif_periodm'	=> '1週1回',
		'notif_ok_ttl'	=> '完了',
		'notif_ok_txt'	=> '成功に情報を保存されます.',
		
		'proffeed_txt'	=> 'RSS/Atom フィード:',
		'proffeed_ok'	=> '完了',
		'proffeed_err'	=> 'エラー',
		'proffeed_oktxt1'		=> '成功にフィードを追加しました.',
		'proffeed_oktxt2'		=> '成功にフィードを取消しました.',
		'proffeed_err_invalid'	=> 'フィードの表示が正しく読むことはできません.',
		'proffeed_submit1'	=> '完了',
		'proffeed_submit2'	=> '変更',
		
	);
	
?>