<?php
	
	$lang	= array
	(
		'subnav_onlyuser'		=> 'だけ ',
		'subnav_withfriends'	=> '友達`',
		'subnav_onlyfav'		=> 'お気には入り',
		'subnav_onlydirect'	=> '直接メッセージ',
		
		'lefcol_edit_profile'	=> 'プロフィールを編集',
		'lefcol_watch_on_'		=> '彼に従う',
		'lefcol_watch_on_m'		=> '彼に従う',
		'lefcol_watch_on_f'		=> '彼女に従う',
		'lefcol_watch_off'	=> '従う停止',
		'lefcol_watch_off_c'	=> '従う停止 - よろしいですか?',
		'lefcol_post_direct'	=> '直接メッセージ',
		'lefcol_get_rss'		=> 'RSS',
		'lefcol_invite'		=> '友達を誘う',
		
		'lefcol_watch_u1'	=> '踏襲',
		'lefcol_watch_u2'	=> 'フォロワー',
		'lefcol_watch_1_'		=> '従う',
		'lefcol_watch_1_m'	=> '踏襲',
		'lefcol_watch_1_f'	=> '踏襲',
		'lefcol_watch_2_'		=> 'ファロワー',
		'lefcol_watch_2_m'	=> 'ファロワー',
		'lefcol_watch_2_f'	=> 'ファロワー',
		
		'lefcol_user_gender_m'	=> '男',
		'lefcol_user_gender_f'	=> '女',
		'lefcol_user_gender_m2'	=> '少年',
		'lefcol_user_gender_f2'	=> '女子',
		'lefcol_user_age1'	=> ',',
		'lefcol_user_age2'	=> '才',
		
		'lefcol_tgs_ttl'		=> 'タグ',
		'lefcol_tgs_ttl_mine'	=> 'タグ',
		'lefcol_tgs_ttl_add'	=> '追加',
		'lefcol_tgs_ttl_edt'	=> '編集',
		'lefcol_tgs_none'		=> 'タグがありません',
		'lefcol_tgs_users1'	=> '結果',
		'lefcol_tgs_usersm'	=> '結果',
		
		'no_posts'	=> 'ポストはありません.',
		'last_post'	=> '最後のポスト',
		
		'icon_fave'		=> 'お気には入りに追加する',
		'icon_unfave'	=> 'お気に入りに取消',
		'icon_unfave_c'	=> 'お気に入りに取消 – よろしいですか?',
		'icon_del'		=> '取消',
		'icon_del_c'	=> '取消中 – よろしいですか?',
		'icon_repl'		=> '直接メッセージ',
		'icon_permalink'	=> 'ポストへの直接リンク',
		
		'posttopicon_direct'	=> '直接メッセージ',
		'posttopicon_mention'	=> 'ポスト@',
		
		'noposts_ttl_onlyuser'	=> 'まだ何もポストをしていません',
		'noposts_txt_onlyuser'	=> 'このタブの中でポストが表示されます。従う友達のポストは友達のタブが表示されます. <a href="'.SITEURL.'faq">More&nbsp;help&nbsp;&raquo;</a>',
		'noposts_ttl_withfriends'	=> '友達からのポストがありません',
		'noposts_txt_withfriends'	=> 'あんたと従う友達のポストといっしょう<a href="'.SITEURL.'#USERNAME#/watched/type:in">が表示されます。</a>. 友達の探すためにクリックして、<a href="'.SITEURL.'search">search</a> あるいは、 <a href="'.SITEURL.'invite">招待状を&nbsp;送れて上げます</a>. <a href="'.SITEURL.'faq">More&nbsp;help&nbsp;&raquo;</a>',
		'noposts_ttl_ifmentioned'	=> '誰も言及していません',
		'noposts_txt_ifmentioned'	=> '誰かに言及しているポストがあります. <a href="'.SITEURL.'faq">More&nbsp;help&nbsp;&raquo;</a>',
		'noposts_ttl_onlyfav'	=> 'お気に入りのポストがありません',
		'noposts_txt_onlyfav'	=> 'お気に入りのポストはここに掲載されます. ポストや他な好きな物を保存するとポストの中でスターをクリックして下さい. <a href="'.SITEURL.'faq">More&nbsp;help&nbsp;&raquo;</a>',
		'noposts_ttl_onlydirect'	=> '直接メッセージがありません',
		'noposts_txt_onlydirect'	=> 'あなたと他の'.SITE_TITLE.'のユーザからのパーソナルメッセージです. 誰かにパーソナルメッセージを送信するは、プロフィールをログインして、メッセージボタンをクリックして下さい "Message&nbsp;directly". <a href="'.SITEURL.'faq">More&nbsp;help&nbsp;&raquo;</a>',
		'noposts2_ttl_onlyuser'	=> 'また#USERNAME#からのポストがありません',
		'noposts2_txt_onlyuser'	=> '... 確かに何を入力するから、待って上げて下さい.',
		'noposts2_ttl_withfriends'	=> '#USERNAME#と友達からポストがありません',
		'noposts2_txt_withfriends'	=> '... 確かに友達が参加するから、待って上げて下さい.',
		'noposts_actions_ttl'	=> '今何をしなければなれませんか?',
		'noposts_actions_txt'	=> ''.SITE_TITLE.'のすべての可能性を取得する場合は、<br />することがあります',
		'noposts_actions_profile'	=> 'プロフィールに個人情報を記入して下さい',
		'noposts_actions_avatar'	=> 'アバターを参照する',
		'noposts_actions_tags'		=> 'プロフィールの中でキーワーどを入力する',
		'noposts_actions_search'	=> '興味で友達を探す',
		'noposts_actions_invite'	=> 'もし、'.SITE_TITLE.'に知り合いと友達がいなければ、招待状を送れて上げます',
		'noposts_actions_post'	=> '今最初のポストを入力して!',
		'noposts_actions_faq'	=> 'まだ手伝うもらう場合には、ここを読んで下さい...',
		
		'noavatar_ttl'	=> 'どうしてアバター <br />がありませんか?',
		'noavatar_lnk'	=> 'アップロード',
		
		'viewpost_page_title'	=> 'ポストをレビュー',
		'viewpost_page_linkprev'	=> '前件',
		'viewpost_page_linknext'	=> '最後',
		
		'ignorebtn1'	=> '無視',
		'ignorebtn1txt_'	=> 'もし、##USERNAME##を無視すれば、'.SITE_TITLE.'にこの人のポストが表示されません.\n\nConfirm ignoring.',
		'ignorebtn1txt_m'	=> 'もし、##USERNAME##を無視すれば、'.SITE_TITLE.'に彼のポストが表示されません.',
		'ignorebtn1txt_f'	=> 'もし、##USERNAME##を無視すれば、'.SITE_TITLE.'に彼女のポストが表示されません.',
		'ignorebtn2_'	=> '無視した',
		'ignorebtn2_m'	=> '無視した',
		'ignorebtn2_f'	=> '無視した',
		
		'MOBI_no_posts'=> 'ポストがありません',
		'MOBI_w_you'	=> '直接',
		'MOBI_w_usr'	=> '従う',
		'MOBI_w_usr2'	=> '従う&nbsp;停止',
		'MOBI_w_msg'	=> '直接&nbsp;メッセージ',
		'MOBI_onlyuser'	=> 'だけ&nbsp;',
		'MOBI_withfr'	=> '友達&nbsp;といっしょうに',
		'MOBI_direct'	=> '直接&nbsp;メッセージ',
		'MOBI_pr_about'	=> 'に&nbsp;',
		'MOBI_watch_ttl2_in_'	=> '彼に&nbsp;従う',
		'MOBI_watch_ttl2_in_m'	=> '彼に&nbsp;従う',
		'MOBI_watch_ttl2_in_f'	=> '彼女に&nbsp;従う',
		'MOBI_watch_ttl2_out_'	=> '踏襲',
		'MOBI_watch_ttl2_out_m'	=> '踏襲',
		'MOBI_watch_ttl2_out_f'	=> '踏襲',
		'MOBI_pr_gender_m'	=> '男性&nbsp;on&nbsp;',
		'MOBI_pr_gender_f'	=> '女性&nbsp;on&nbsp;',
		'MOBI_attached_link'	=> '(リンクを添付)',
		'MOBI_attached_image'	=> '(写真を添付)',
		'MOBI_attached_video'	=> '(ビデオを添付)',
		'MOBI_attimage_ttl'	=> '写真レビュー:',
		'MOBI_attimage_szs'	=> 'サイズ:',
		
		
		'guestbox_ttl'	=> 'ハロー、ここは##USERNAME##のマイクロブログ',
		'guestbox_txt'	=> '世界に日常生活を共有するために '.SITE_TITLE.'を使用します.',
		'guestbox_reg1'	=> '登録',
		'guestbox_txt2'	=> ', 友達が何をしていて、ポストを読みます.',
		'guestbox_reg2'	=> '加わる',
		'guestbox_or'	=> 'あるいは、',
		'guestbox_tour'	=> ''.SITE_TITLE.'の詳細について',
		
		'guest_vpk_title'		=> 'このポストは<a href="##USERLINK##">microblog of ##NAME##</a>の一部です.',
		'guest_vpk_text_'		=> ''.SITE_TITLE.'から友達と通信して、日常生活を共有するサイトを使用します.',
		'guest_vpk_text_m'	=> ''.SITE_TITLE.'から友達と通信して、日常生活を共有するサイトを使用します',
		'guest_vpk_text_f'	=> ''.SITE_TITLE.'から友達と通信して、日常生活を共有するサイトを使用します',
		
	);
	
?>