<?php
	
	$lang	= array
	(
		'edtprf_ttl_info'		=> '编辑个人资料',
		'edtprf_ttl_avatar'	=> '编辑头像',
		'edtprf_ttl_tags'		=> '编辑关键词',
		'edtprf_ttl_password'	=> '更改密码',
		'edtprf_ttl_email'	=> '更改电子邮件',
		'edtprf_ttl_ignored'	=> '已忽略用户',
		'edtprf_ttl_notif'	=> '邮件通知',
		'edtprf_ttl_feed'	=> '通过RSS发帖',
		
		'prof_tab_info'		=> '资料',
		'prof_tab_avatar'		=> '头像',
		'prof_tab_tags'		=> '关键词',
		'prof_tab_password'	=> '密码',
		'prof_tab_email'		=> '电子邮件',
		'prof_tab_ignored'	=> '忽略用户',
		'prof_tab_notif'		=> '通知',
		'prof_tab_feed'		=> 'RSS',
		
		'profinfo_fullname'	=> '全名',
		'profinfo_fullname_dsc'	=> '请输入您的全名',
		'profinfo_website'	=> '个人网站',
		'profinfo_website_dsc'	=> '您的个人网站，博客或者是个人资料',
		'profinfo_website_err'	=> '请输入正确的网址',
		'profinfo_city'		=> '居住地',
		'profinfo_city_dsc'	=> '国家或城市',
		'profinfo_gender'		=> '性别',
		'profinfo_gender_m'	=> '男性',
		'profinfo_gender_f'	=> '女性',
		'profinfo_birthdt'	=> '生日',
		'profinfo_birthdt_dsc'	=> '格式：月-日-年',
		'profinfo_aboutme'	=> '自我介绍',
		'profinfo_aboutme_dsc'	=> '80字内的简单信息',
		'profinfo_tags'		=> '关键词',
		'profinfo_tags_dsc'	=> '关键词',
		'profinfo_tags_dscr'	=> '什么是关键词？<br />10个可以贴切描述您的词语。<br />注意：请用英文逗号 , 分隔。',
		'submitinfo_ok'	=> '保存',
		'submitinfo_ok1'	=> '更改已保存',
		'submitinfo_err'	=> '错误',
		'submitinfo_err1'	=> '无效站点',
		
		'profavat_noavat'	=> '您还没有头像！',
		'profavat_add'	=> '在这里上传',
		'profavat_avat'	=> '当前头像',
		'profavat_add2'	=> '替换头像',
		'profavat_help'	=> '允许的格式：GIF/JPEG/PNG。<br />图片规格至少达到'.AVATAR_SIZE.'x'.AVATAR_SIZE.'像素。<br />如果图片不是正方形，将会被自动裁剪。',
		'profavat_add_ok'		=> '完成',
		'profavat_add_ok1'	=> '头像成功上传',
		'profavat_add_err'	=> '错误',
		'profavat_add_err1'	=> '错误的文件格式',
		'profavat_add_err2'	=> '图片尺寸太小',
		'profavat_add_err3'	=> '无法处理头像图片',
		
		'profmail_now'	=> '当前电子邮件',
		'profmail_new'	=> '新电子邮件',
		'profmail_new_2'	=> '请输入您的新电子邮件',
		'profmail_new2'	=> '再次输入新电子邮件',
		'profmail_new2_2'	=> '防止误输入',
		'profmail_pass'	=> '当前密码',
		'profmail_pass_2'	=> '安全起见',
		'submitmail_ok'	=> '完成',
		'submitmail_ok1'	=> '电子邮件已更改',
		'submitmail_err'	=> '错误',
		'submitmail_err1'	=> '无效的电子邮件',
		'submitmail_err2'	=> '正是您现在使用的电子邮件 :)',
		'submitmail_err3'	=> '两次输入的电子邮件不匹配',
		'submitmail_err4'	=> '其他用户正在使用此电子邮件',
		'submitmail_err5'	=> '密码错误',
		
		'profpass_now'	=> '当前密码',
		'profpass_now_2'	=> '请输入当前密码',
		'profpass_new'	=> '新密码',
		'profpass_new_2'	=> '请输入新密码',
		'profpass_new2'	=> '再次输入新密码',
		'profpass_new2_2'	=> '防止误输入',
		'submitpass_ok'	=> '完成',
		'submitpass_ok1'	=> '密码已更改',
		'submitpass_err'	=> '完成',
		'submitpass_err1'	=> '密码至少5位',
		'submitpass_err2'	=> '两次输入的密码不匹配',
		'submitpass_err3'	=> '当前密码错误',
		
		'edit_submit'	=> '保存',
		'edit_submit2'	=> '上传',
		
		'ignored_nores_ttl'	=> '忽略列表为空',
		'ignored_nores_txt'	=> '您未忽略任何人',
		'ignored_delete_btn'	=> '停止忽略',
		'ignored_del_confirm'	=> '停止忽略该用户，确认？',
		
		'notif_onwatch'	=> '当有人关注我时通知我',
		'notif_ondirect'	=> '当有人向我发送私人消息时通知我',
		'notif_onmention'	=> '当有人在帖子中提及我时通知我',
		'notif_periodic1'	=> '通知我',
		'notif_periodic2'	=> '关于我和我的好友的信息',
		'notif_periodd'	=> '每天一次',
		'notif_periodm'	=> '每周一次',
		'notif_ok_ttl'	=> '完成',
		'notif_ok_txt'	=> '更改已保存',
		
		'proffeed_txt'	=> 'RSS/Atom源',
		'proffeed_ok'	=> '完成',
		'proffeed_err'	=> '错误',
		'proffeed_oktxt1'		=> 'RSS/Atom源已添加',
		'proffeed_oktxt2'		=> 'RSS/Atom源已删除',
		'proffeed_err_invalid'	=> '无效的RSS/Atom源',
		'proffeed_submit1'	=> '完成',
		'proffeed_submit2'	=> '更改',
		
	);
	
?>
