<?php
             
              $lang              = array
              (
                            'subnav_onlyuser'                            => 'Seulement ',
                            'subnav_withfriends'              => 'Amis`',
                            'subnav_onlyfav'                            => 'Préférés',
                            'subnav_onlydirect'              => ' Messages directs',
                           
                            'lefcol_edit_profile'              => 'Changer profil',
                            'lefcol_watch_on_'                            => 'Suit le',
                            'lefcol_watch_on_m'                            => 'Suit le',
                            'lefcol_watch_on_f'                            => 'Suit la',
                            'lefcol_watch_off'              => 'Arrêtez de suivre',
                            'lefcol_watch_off_c'              => 'Arrêtez de suivre - êtes vous sûre?',
                            'lefcol_post_direct'              => 'Message direct',
                            'lefcol_get_rss'                            => 'RSS',
                            'lefcol_invite'                            => 'Inviter vos amis',
                           
                            'lefcol_watch_u1'              => 'Suivant',
                            'lefcol_watch_u2'              => 'Adeptes',
                            'lefcol_watch_1_'                            => 'Suivre',
                            'lefcol_watch_1_m'              => 'Suivant',
                            'lefcol_watch_1_f'              => 'Suivant',
                            'lefcol_watch_2_'                            => 'Adeptes',
                            'lefcol_watch_2_m'              => 'Adeptes',
                            'lefcol_watch_2_f'              => 'Adeptes',
                           
                            'lefcol_user_gender_m'              => 'Male',
                            'lefcol_user_gender_f'              => 'Femelle',
                            'lefcol_user_gender_m2'              => 'Garçon',
                            'lefcol_user_gender_f2'              => 'Fille',
                            'lefcol_user_age1'              => ',',
                            'lefcol_user_age2'              => ' ans',
                           
                            'lefcol_tgs_ttl'                            => 'Etiquettes',
                            'lefcol_tgs_ttl_mine'              => 'Etiquettes',
                            'lefcol_tgs_ttl_add'              => 'ajouter',
                            'lefcol_tgs_ttl_edt'              => 'changer',
                            'lefcol_tgs_none'                            => 'Vous n\'avez pas d\'étiquettes',
                            'lefcol_tgs_users1'              => 'resultat',
                            'lefcol_tgs_usersm'              => 'le resultat',
                           
                            'no_posts'              => 'Il n\'y a pas de postes.',
                            'last_post'              => 'dernière poste',
                           
                            'icon_fave'                            => 'ajouter aux préférés',
                            'icon_unfave'              => 'Effacer des préférés',
                            'icon_unfave_c'              => 'Effacer des préférés – Etes vous sûre?',
                            'icon_del'                            => 'Effacer',
                            'icon_del_c'              => 'En train d\'effacer – Etes vous sûre?',
                            'icon_repl'                            => 'Message lui directement',
                            'icon_permalink'              => 'Lien direct à la poste',
                           
                            'posttopicon_direct'              => 'Message lui directement',
                            'posttopicon_mention'              => 'poste @',
                           
                            'noposts_ttl_onlyuser'              => 'Vous n\'avez rien affiché',
                            'noposts_txt_onlyuser'              => 'Vos postes vont être vu dans cette étiquette.Vous la voit ici, mais les personnes qui vous suivent, vont la voir dans cette étiquette "Friends". <a href="'.SITEURL.'faq">More&nbsp;help&nbsp;&raquo;</a>',
                            'noposts_ttl_withfriends'              => 'Vous n\'avez pas de postes de vos amis',
                            'noposts_txt_withfriends'              => 'Vos postes vont être montrée ici, avec les autres usagers qui <a href="'.SITEURL.'#USERNAME#/watched/type:in">follow</a>. Vous pouvez cliquer  <a href="'.SITEURL.'search">search</a> pour trouvé vbs amis ou vous pouvez <a href="'.SITEURL.'invite">send&nbsp;invitations</a>. <a href="'.SITEURL.'faq">More&nbsp;help&nbsp;&raquo;</a>',
                            'noposts_ttl_ifmentioned'              => 'Personne n\'a vous mentionné',
                            'noposts_txt_ifmentioned'              => 'Voici les postes qui vous avez mentionné. <a href="'.SITEURL.'faq">Another&nbsp;help&nbsp;&raquo;</a>',
                            'noposts_ttl_onlyfav'              => 'Vous n\'avez pas de postes préférées',
                            'noposts_txt_onlyfav'              => 'Les postes que vous marquez comme "préférés" vont apparaître ici. Pour sauver vos postes et les autres choses que vous aimez, cliquez sur l\'étoile dans les postes que vous aimez. <a href="'.SITEURL.'faq">More&nbsp;help&nbsp;&raquo;</a>',
                            'noposts_ttl_onlydirect'              => 'Vous n\'avez pas de messages directs',
                            'noposts_txt_onlydirect'              => 'messages personnels entre vous et quelqu\'un dans '.SITE_TITLE.'. Pour envoyer un message personnel à quelqu\'un, connectez votre profil et cliquez sur le boutton "Message&nbsp;directly". <a href="'.SITEURL.'faq">More&nbsp;help&nbsp;&raquo;</a>',
                            'noposts2_ttl_onlyuser'              => 'Il n\'y a toujours pas de postes de #USERNAME#',
                            'noposts2_txt_onlyuser'              => '... mais nous sommes sûre qu\'il est en train de taper quelque chose, alors restez ici.',
                            'noposts2_ttl_withfriends'              => 'Il n\'y a toujours pas de postes de #USERNAME# and friends',
                            'noposts2_txt_withfriends'              => '... mais nous sommes sûre qu\'il est en train de joindre, alors restez ici.',
                            'noposts_actions_ttl'              => 'Je fais quoi maintenant ?',
                            'noposts_actions_txt'              => 'Il y a quelque chose que vous avez besoin de faire pour<br />de tous les possibilités de '.SITE_TITLE,
                            'noposts_actions_profile'              => 'Remplir votre profil avec vos informations personnelles',
                            'noposts_actions_avatar'              => 'Brouter votre avatar',
                            'noposts_actions_tags'                            => 'Taper le mot clé dans votre profil',
                            'noposts_actions_search'              => 'Rechercher des amis ou des personnes avec les mêmes intérêts que vous',
                            'noposts_actions_invite'              => 'S\'il n\'y a toujours personne dans '.SITE_TITLE.', vous pouvez inviter',
                            'noposts_actions_post'              => 'Taper votre première poste maintenant!',
                            'noposts_actions_faq'              => 'Si vous voudrez toujours de l\'aide, lire cela...',
                           
                            'noavatar_ttl'              => 'Vous n\'avez toujours pas <br />d\'avatar ?',
                            'noavatar_lnk'              => 'Télécharger',
                           
                            'viewpost_page_title'              => 'Afficher la revue',
                            'viewpost_page_linkprev'              => 'précédent',
                            'viewpost_page_linknext'              => 'dernière',
                           
                            'ignorebtn1'              => 'Négliger',
                            'ignorebtn1txt_'              => 'Si vous négligez ##USERNAME##, vous n\'allez pas voire ses postes dans '.SITE_TITLE.'.\n\nConfirm ignoring.',
                            'ignorebtn1txt_m'              => 'Si vous négligez ##USERNAME##, vous n\'allez pas voire ses postes dans '.SITE_TITLE.'.\n\nConfirm ignoring.',
                            'ignorebtn1txt_f'              => 'Si vous négligez ##USERNAME##, vous n\'allez pas voire ses postes dans '.SITE_TITLE.'.\n\nConfirm ignoring.',
                            'ignorebtn2_'              => 'Négliger',
                            'ignorebtn2_m'              => 'Négliger',
                            'ignorebtn2_f'              => 'Négliger',
                           
                            'MOBI_no_posts'              => 'Il n\'y a pas de postes',
                            'MOBI_w_you'              => 'direct',
                            'MOBI_w_usr'              => 'suivre',
                            'MOBI_w_usr2'              => 'arrêtez de&nbsp;suivre',
                            'MOBI_w_msg'              => 'Message&nbsp;directement',
                            'MOBI_onlyuser'              => 'Seulement&nbsp;',
                            'MOBI_withfr'              => 'avec&nbsp;amis',
                            'MOBI_direct'              => 'Messages&nbsp;directs',
                            'MOBI_pr_about'              => 'Pour&nbsp;',
                            'MOBI_watch_ttl2_in_'              => 'Suivez&nbsp;lui',
                            'MOBI_watch_ttl2_in_m'              => 'Suivez&nbsp;lui',
                            'MOBI_watch_ttl2_in_f'              => 'Suivez&nbsp;la',
                            'MOBI_watch_ttl2_out_'              => 'En train de suivre',
                            'MOBI_watch_ttl2_out_m'              => 'En train de suivre',
                            'MOBI_watch_ttl2_out_f'              => 'En train de suivre',
                            'MOBI_pr_gender_m'              => 'Male&nbsp;on&nbsp;',
                            'MOBI_pr_gender_f'              => 'Femelle&nbsp;on&nbsp;',
                            'MOBI_attached_link'              => '(lien attaché)',
                            'MOBI_attached_image'              => '(photo attachée)',
                            'MOBI_attached_video'              => '(vidéo attachée)',
                            'MOBI_attimage_ttl'              => 'Revue de la photo:',
                            'MOBI_attimage_szs'              => 'Tailles:',
                           
                           
                            'guestbox_ttl'              => 'Bonjour, c\'est le microblog de',
                            'guestbox_txt'              => 'utilisez '.SITE_TITLE.', pour partager sa vie quotidienne.',
                            'guestbox_reg1'              => 'Enregistrer',
                            'guestbox_txt2'              => ', pour suivre qu\'est ce qu\'ils sont en train de faire.',
                            'guestbox_reg2'              => 'Joindre',
                            'guestbox_or'              => 'ou',
                            'guestbox_tour'              => 'apprennez plus sur '.SITE_TITLE,
                           
                            'guest_vpk_title'                            => 'Cette poste appartient à <a href="##USERLINK##">microblog of ##NAME##</a>.',
                            'guest_vpk_text_'                            => 'Il utilise '.SITE_TITLE.', pour communiquer avec ses amis et pour partager une pièce de sa vie quotidienne avec eux.',
                            'guest_vpk_text_m'              => 'Il utilise '.SITE_TITLE.', pour communiquer avec ses amis et pour partager une pièce de sa vie quotidienne avec eux.',
                            'guest_vpk_text_f'              => 'Elle utilise '.SITE_TITLE.', pour communiquer avec ses amis et pour partager une pièce de sa vie quotidienne avec eux.',
                           
              );
             
?>