<?php
	
	$lang	= array
	(
		'subnav_onlyuser'		=> 'Само ',
		'subnav_withfriends'	=> 'С приятели',
		'subnav_onlyfav'		=> 'Любими',
		'subnav_onlydirect'	=> 'Директни',
		
		'lefcol_edit_profile'	=> 'Редакция на профил',
		'lefcol_watch_on_'		=> 'Проследи го',
		'lefcol_watch_on_m'		=> 'Проследи го',
		'lefcol_watch_on_f'		=> 'Проследи я',
		'lefcol_watch_off'	=> 'Спри&nbsp;следенето',
		'lefcol_watch_off_c'	=> 'Прекратяване на следенето - сигурни ли сте?',
		'lefcol_post_direct'	=> 'Пиши директно',
		'lefcol_get_rss'		=> 'RSS',
		'lefcol_invite'		=> 'Покани приятели',
		
		'lefcol_watch_u1'	=> 'Ти следиш',
		'lefcol_watch_u2'	=> 'Следят те',
		'lefcol_watch_1_'		=> 'Следи',
		'lefcol_watch_1_m'	=> 'Той следи',
		'lefcol_watch_1_f'	=> 'Тя следи',
		'lefcol_watch_2_'		=> 'Следят го',
		'lefcol_watch_2_m'	=> 'Следят го',
		'lefcol_watch_2_f'	=> 'Следят я',
		
		'lefcol_user_gender_m'	=> 'Мъж',
		'lefcol_user_gender_f'	=> 'Жена',
		'lefcol_user_gender_m2'	=> 'Момче',
		'lefcol_user_gender_f2'	=> 'Момиче',
		'lefcol_user_age1'	=> 'на',
		'lefcol_user_age2'	=> 'г.',
		
		'lefcol_tgs_ttl'		=> 'Тагове',
		'lefcol_tgs_ttl_mine'	=> 'Tагове',
		'lefcol_tgs_ttl_add'	=> 'добави',
		'lefcol_tgs_ttl_edt'	=> 'редактирай',
		'lefcol_tgs_none'		=> 'Нямате тагове',
		'lefcol_tgs_users1'	=> 'резултат',
		'lefcol_tgs_usersm'	=> 'резултата',
		
		'no_posts'	=> 'Няма посове.',
		'last_post'	=> 'последен пост',
		
		'icon_fave'		=> 'в Любими',
		'icon_unfave'	=> 'махни от Любими',
		'icon_unfave_c'	=> 'Премахване от Любими - Сигурни ли сте?',
		'icon_del'		=> 'изтриване',
		'icon_del_c'	=> 'Изтриване - Сигурни ли сте?',
		'icon_repl'		=> 'Пиши директно',
		'icon_permalink'	=> 'Директен линк към поста',
		
		'posttopicon_direct'	=> 'пиши директно',
		'posttopicon_mention'	=> 'пост @',
		
		'noposts_ttl_onlyuser'	=> 'Все още не си постнал нищо',
		'noposts_txt_onlyuser'	=> 'В този таб ще излизат твоите постове. Ти ги виждаш тук, а хората, който те следят, ги виждат в таба "С&nbsp;приятели". <a href="'.SITEURL.'faq">Още&nbsp;помощ&nbsp;&raquo;</a>',
		'noposts_ttl_withfriends'	=> 'Все още нямаш постове на приятели',
		'noposts_txt_withfriends'	=> 'Тук излизат твоите постове плюс постовете на потребителите, които <a href="'.SITEURL.'#USERNAME#/watched/type:in">следиш</a>. Можеш да <a href="'.SITEURL.'search">потърсиш</a> приятели или да им <a href="'.SITEURL.'invite">изпратиш&nbsp;покани</a>. <a href="'.SITEURL.'faq">Още&nbsp;помощ&nbsp;&raquo;</a>',
		'noposts_ttl_ifmentioned'	=> 'Никой не говори за теб',
		'noposts_txt_ifmentioned'	=> 'Тук излизат постове, в които някой те споменава. <a href="'.SITEURL.'faq">Още&nbsp;помощ&nbsp;&raquo;</a>',
		'noposts_ttl_onlyfav'	=> 'Нямаш любими постове',
		'noposts_txt_onlyfav'	=> 'Тук виждаш постовете, които си маркирал като любими. За да си запазиш постове и неща, които ти харесват, кликни на звездичката в горния десен ъгъл на всеки пост. <a href="'.SITEURL.'faq">Още&nbsp;помощ&nbsp;&raquo;</a>',
		'noposts_ttl_onlydirect'	=> 'Нямаш директни съобщения',
		'noposts_txt_onlydirect'	=> 'Тук излизат личните съобшения между теб и другите потребители в '.SITE_TITLE.'. За да изпратиш лично съобщение на някого, влез в профила му и кликни бутона "Пиши&nbsp;директно". <a href="'.SITEURL.'faq">Още&nbsp;помощ&nbsp;&raquo;</a>',
		'noposts2_ttl_onlyuser'	=> 'Все още няма постове от #USERNAME#',
		'noposts2_txt_onlyuser'	=> '... но сме сигурни, че ще напише нещо, така че се навъртай наоколо.',
		'noposts2_ttl_withfriends'	=> 'Все още няма постове от #USERNAME# и приятели',
		'noposts2_txt_withfriends'	=> '... но сме сигурни, че ще се зарибят, така че се навъртай наоколо.',
		'noposts_actions_ttl'	=> 'Какво да правя сега ?',
		'noposts_actions_txt'	=> 'Има още няколко неща, които да направиш, за да се възползваш<br />от пълните възможности на '.SITE_TITLE,
		'noposts_actions_profile'	=> 'Попълни профила си с повече информация за теб',
		'noposts_actions_avatar'	=> 'Качи си аватар',
		'noposts_actions_tags'		=> 'Напиши си ключови думи към профила',
		'noposts_actions_search'	=> 'Потърси приятели или хора с интереси като твоите',
		'noposts_actions_invite'	=> 'Ако все още няма твои познати в '.SITE_TITLE.', можеш да поканиш',
		'noposts_actions_post'	=> 'Напиши най-после първия си пост!',
		'noposts_actions_faq'	=> 'Ако все още имаш нужда от помощ, прочети тук...',
		
		'noavatar_ttl'	=> 'Още нямаш<br />аватар ?',
		'noavatar_lnk'	=> 'качи си',
		
		'viewpost_page_title'	=> 'Преглед на пост',
		'viewpost_page_linkprev'	=> 'предишен',
		'viewpost_page_linknext'	=> 'следващ',
		
		'ignorebtn1'	=> 'Игнорирай',
		'ignorebtn1txt_'	=> 'Ако игнорираш ##USERNAME##, повече няма да виждаш постовете му в '.SITE_TITLE.'.\n\nПотвърди игнорирането.',
		'ignorebtn1txt_m'	=> 'Ако игнорираш ##USERNAME##, повече няма да виждаш постовете му в '.SITE_TITLE.'.\n\nПотвърди игнорирането.',
		'ignorebtn1txt_f'	=> 'Ако игнорираш ##USERNAME##, повече няма да виждаш постовете й в '.SITE_TITLE.'.\n\nПотвърди игнорирането.',
		'ignorebtn2_'	=> 'Игнориран',
		'ignorebtn2_m'	=> 'Игнориран',
		'ignorebtn2_f'	=> 'Игнорирана',
		
		'MOBI_no_posts'	=> 'Няма постове',
		'MOBI_w_you'	=> 'директни',
		'MOBI_w_usr'	=> 'проследи',
		'MOBI_w_usr2'	=> 'спри&nbsp;следенето',
		'MOBI_w_msg'	=> 'пиши&nbsp;директно',
		'MOBI_onlyuser'	=> 'Само&nbsp;',
		'MOBI_withfr'	=> 'С&nbsp;приятели',
		'MOBI_direct'	=> 'Директни&nbsp;съобщения',
		'MOBI_pr_about'	=> 'За&nbsp;',
		'MOBI_watch_ttl2_in_'	=> 'Следят&nbsp;го',
		'MOBI_watch_ttl2_in_m'	=> 'Следят&nbsp;го',
		'MOBI_watch_ttl2_in_f'	=> 'Следят&nbsp;я',
		'MOBI_watch_ttl2_out_'	=> 'Tой&nbsp;следи',
		'MOBI_watch_ttl2_out_m'	=> 'Tой&nbsp;следи',
		'MOBI_watch_ttl2_out_f'	=> 'Tя&nbsp;следи',
		'MOBI_pr_gender_m'	=> 'Мъж&nbsp;на&nbsp;',
		'MOBI_pr_gender_f'	=> 'Жена&nbsp;на&nbsp;',
		'MOBI_attached_link'	=> '(прикачен линк)',
		'MOBI_attached_image'	=> '(прикачена снимка)',
		'MOBI_attached_video'	=> '(прикачен видеоклип)',
		'MOBI_attimage_ttl'	=> 'Преглед на снимка:',
		'MOBI_attimage_szs'	=> 'Размери:',
		
		
		'guestbox_ttl'	=> 'Здрасти, това е микроблогът на',
		'guestbox_txt'	=> 'използва '.SITE_TITLE.', за да споделя ежедневието си със света.',
		'guestbox_reg1'	=> 'Регистрирай се',
		'guestbox_txt2'	=> ', за да следиш какво прави и да четеш какво поства.',
		'guestbox_reg2'	=> 'Присъедини се',
		'guestbox_or'	=> 'или',
		'guestbox_tour'	=> 'разбери още за '.SITE_TITLE,
		
		'guest_vpk_title'		=> 'Този пост е част от <a href="##USERLINK##">микроблога на ##NAME##</a>.',
		'guest_vpk_text_'		=> 'Той използва '.SITE_TITLE.', за да общува с приятелите си и да споделя с тях ежедневието си.',
		'guest_vpk_text_m'	=> 'Той използва '.SITE_TITLE.', за да общува с приятелите си и да споделя с тях ежедневието си.',
		'guest_vpk_text_f'	=> 'Тя използва '.SITE_TITLE.', за да общува с приятелите си и да споделя с тях ежедневието си.',
		
	);
	
?>