<?php
	
	$lang	= array
	(
		'edtprf_ttl_info'		=> 'Edit your profile',
		'edtprf_ttl_avatar'	=> 'Edit your avatar',
		'edtprf_ttl_tags'		=> 'Edit you tags',
		'edtprf_ttl_password'	=> 'Change your password',
		'edtprf_ttl_email'	=> 'Change your e-mail address',
		'edtprf_ttl_ignored'	=> 'Ignored users',
		'edtprf_ttl_notif'	=> 'Notifications by e-mail',
		'edtprf_ttl_feed'	=> 'Posts from feed',
		
		'prof_tab_info'		=> 'Info',
		'prof_tab_avatar'		=> 'Avatar',
		'prof_tab_tags'		=> 'Tags',
		'prof_tab_password'	=> 'Password',
		'prof_tab_email'		=> 'E-mail',
		'prof_tab_ignored'	=> 'Ignored ',
		'prof_tab_notif'		=> 'Notifications',
		'prof_tab_feed'		=> 'Feed',
		
		'profinfo_fullname'	=> 'Full name',
		'profinfo_fullname_dsc'	=> 'Enter your first and last name',
		'profinfo_website'	=> 'Personal Website',
		'profinfo_website_dsc'	=> 'Personal site, blog or profile',
		'profinfo_website_err'	=> 'Please, give a valid site address',
		'profinfo_city'		=> 'Location',
		'profinfo_city_dsc'	=> 'Country or City',
		'profinfo_gender'		=> 'Gender',
		'profinfo_gender_m'	=> 'Male',
		'profinfo_gender_f'	=> 'Female',
		'profinfo_birthdt'	=> 'Date of birth',
		'profinfo_birthdt_dsc'	=> 'Format: Month-Day-Year',
		'profinfo_aboutme'	=> 'Write something about yourself',
		'profinfo_aboutme_dsc'	=> 'Short description up to 80 symbols',
		'profinfo_tags'		=> 'Personal tags',
		'profinfo_tags_dsc'	=> 'Your personal tags',
		'profinfo_tags_dscr'	=> 'Your personal tags:<br />Put to 10 tags to describe yourself.<br />Separate them with comma.',
		'submitinfo_ok'	=> 'Save',
		'submitinfo_ok1'	=> 'The information was saved successfully.',
		'submitinfo_err'	=> 'Error',
		'submitinfo_err1'	=> 'Invalid site',
		
		'profavat_noavat'	=> 'You still don’t have an avatar!',
		'profavat_add'	=> 'You can upload here',
		'profavat_avat'	=> 'Current avatar',
		'profavat_add2'	=> 'Replace avatar',
		'profavat_help'	=> 'Allowed formats: GIF/JPEG/PNG.<br />The picture has to be bigger than '.AVATAR_SIZE.'x'.AVATAR_SIZE.' pixels.<br />If the shape is not a square, parts of  it will be cut.',
		'profavat_add_ok'		=> 'Done',
		'profavat_add_ok1'	=> 'The avatar was uploaded successfully',
		'profavat_add_err'	=> 'Error',
		'profavat_add_err1'	=> 'Indicated file is invalid.',
		'profavat_add_err2'	=> 'Indicated picture is too small.',
		'profavat_add_err3'	=> 'The avatar can not be copied.',
		
		'profmail_now'	=> 'Current e-mail',
		'profmail_new'	=> 'New e-mail address',
		'profmail_new_2'	=> 'Indicate your new e-mail address',
		'profmail_new2'	=> 'Enter e-mail again',
		'profmail_new2_2'	=> 'For confirmation',
		'profmail_pass'	=> 'Your current password',
		'profmail_pass_2'	=> 'For your security',
		'submitmail_ok'	=> 'Done',
		'submitmail_ok1'	=> 'Your E-mail address was changed successfully.',
		'submitmail_err'	=> 'Error',
		'submitmail_err1'	=> 'Invalid e-mail address.',
		'submitmail_err2'	=> 'E-mail address is the same as the current one :)',
		'submitmail_err3'	=> 'E-mails do not match.',
		'submitmail_err4'	=> 'There is another user with this e-mail address.',
		'submitmail_err5'	=> 'This password is wrong.',
		
		'profpass_now'	=> 'Current password',
		'profpass_now_2'	=> 'Put your current password',
		'profpass_new'	=> 'New password',
		'profpass_new_2'	=> 'Put your new password',
		'profpass_new2'	=> 'Enter new password again',
		'profpass_new2_2'	=> 'For confirmation',
		'submitpass_ok'	=> 'Done',
		'submitpass_ok1'	=> 'Your password was changed successfully.',
		'submitpass_err'	=> 'Done',
		'submitpass_err1'	=> 'The password has to be at least 5 symbols.',
		'submitpass_err2'	=> 'These passwords are not the same.',
		'submitpass_err3'	=> 'Wrong current password',
		
		'edit_submit'	=> 'Save',
		'edit_submit2'	=> 'Upload',
		
		'ignored_nores_ttl'	=> 'There are no ignored users',
		'ignored_nores_txt'	=> 'You still haven`t ignored anybody.',
		'ignored_delete_btn'	=> 'delete',
		'ignored_del_confirm'	=> 'Stop ignoring – are you sure?',
		
		'notif_onwatch'	=> 'Notify me every time somebody starts to follow me',
		'notif_ondirect'	=> 'Notify me every time somebody types me a direct message',
		'notif_onmention'	=> 'Notify me every time somebody mentions me in his or her post',
		'notif_periodic1'	=> 'Notify me',
		'notif_periodic2'	=> 'For news, regarding me and my friends ',
		'notif_periodd'	=> 'once per day',
		'notif_periodm'	=> 'once per week',
		'notif_ok_ttl'	=> 'Done',
		'notif_ok_txt'	=> 'Information was saved successfully.',
		
		'proffeed_txt'	=> 'RSS/Atom feed:',
		'proffeed_ok'	=> 'Done',
		'proffeed_err'	=> 'Error',
		'proffeed_oktxt1'		=> 'The feed was added successfully.',
		'proffeed_oktxt2'		=> 'The feed was deleted successfully.',
		'proffeed_err_invalid'	=> 'Indicated feed can not be read correctly.',
		'proffeed_submit1'	=> 'Done',
		'proffeed_submit2'	=> 'Change',
		
	);
	
?>
