<?php
	
	$lang	= array
	(
		'subnav_onlyuser'		=> 'Only ',
		'subnav_withfriends'	=> 'Friends`',
		'subnav_onlyfav'		=> 'Favorites',
		'subnav_onlydirect'	=> 'Direct Messages',
		
		'lefcol_edit_profile'	=> 'Edit Profile',
		'lefcol_watch_on_'		=> 'Follow him',
		'lefcol_watch_on_m'		=> 'Follow him',
		'lefcol_watch_on_f'		=> 'Follow her',
		'lefcol_watch_off'	=> 'Stop following',
		'lefcol_watch_off_c'	=> 'Stop following - are you sure?',
		'lefcol_post_direct'	=> 'Direct Message',
		'lefcol_get_rss'		=> 'RSS',
		'lefcol_invite'		=> 'Invite friends',
		
		'lefcol_watch_u1'	=> 'Following',
		'lefcol_watch_u2'	=> 'Followers',
		'lefcol_watch_1_'		=> 'Follow',
		'lefcol_watch_1_m'	=> 'He follows',
		'lefcol_watch_1_f'	=> 'She follows',
		'lefcol_watch_2_'		=> 'He is followed',
		'lefcol_watch_2_m'	=> 'He is followed',
		'lefcol_watch_2_f'	=> 'She is followed',
		
		'lefcol_user_gender_m'	=> 'Male',
		'lefcol_user_gender_f'	=> 'Female',
		'lefcol_user_gender_m2'	=> 'Boy',
		'lefcol_user_gender_f2'	=> 'Girl',
		'lefcol_user_age1'	=> ',',
		'lefcol_user_age2'	=> ' years old',
		
		'lefcol_tgs_ttl'		=> 'Tags',
		'lefcol_tgs_ttl_mine'	=> 'Tags',
		'lefcol_tgs_ttl_add'	=> 'add',
		'lefcol_tgs_ttl_edt'	=> 'edit',
		'lefcol_tgs_none'		=> 'You don’t have any tags',
		'lefcol_tgs_users1'	=> 'result',
		'lefcol_tgs_usersm'	=> 'the result',
		
		'no_posts'	=> 'There are no posts.',
		'last_post'	=> 'last post',
		
		'icon_fave'		=> 'add to Favorites',
		'icon_unfave'	=> 'Delete from Favorites',
		'icon_unfave_c'	=> 'Delete from Favorites – Are you sure?',
		'icon_del'		=> 'Delete',
		'icon_del_c'	=> 'Deleting – Are you sure?',
		'icon_repl'		=> 'Message directly',
		'icon_permalink'	=> 'Direct link to the post',
		
		'posttopicon_direct'	=> 'Message directly',
		'posttopicon_mention'	=> 'post @',
		
		'noposts_ttl_onlyuser'	=> 'You still haven`t posted anything',
		'noposts_txt_onlyuser'	=> 'In this tab your posts will be shown.You see it here, but the people who follow you, will see it in the tab "With&nbsp;friends". <a href="'.SITEURL.'faq">More&nbsp;help&nbsp;&raquo;</a>',
		'noposts_ttl_withfriends'	=> 'You do not have any posts from your friends',
		'noposts_txt_withfriends'	=> 'Your posts will be shown here along with the posts of users who you <a href="'.SITEURL.'#USERNAME#/watched/type:in">follow</a>. You can click <a href="'.SITEURL.'search">search</a> to find friends or you can <a href="'.SITEURL.'invite">send&nbsp;invitations</a>. <a href="'.SITEURL.'faq">More&nbsp;help&nbsp;&raquo;</a>',
		'noposts_ttl_ifmentioned'	=> 'No one has mentioned you',
		'noposts_txt_ifmentioned'	=> 'Here are posts where somebody has mentioned you. <a href="'.SITEURL.'faq">Another&nbsp;help&nbsp;&raquo;</a>',
		'noposts_ttl_onlyfav'	=> 'You do not have any favorite posts',
		'noposts_txt_onlyfav'	=> 'The posts you mark as "favorite" will be placed here. To save posts and other things that you like, click on the star in the posts you like. <a href="'.SITEURL.'faq">More&nbsp;help&nbsp;&raquo;</a>',
		'noposts_ttl_onlydirect'	=> 'You do not have any direct messages',
		'noposts_txt_onlydirect'	=> 'personal messages between you and the other users in '.SITE_TITLE.'. To send a personal message to somebody, log in your profile and click on the button "Message&nbsp;directly". <a href="'.SITEURL.'faq">More&nbsp;help&nbsp;&raquo;</a>',
		'noposts2_ttl_onlyuser'	=> 'It still does not have any posts from #USERNAME#',
		'noposts2_txt_onlyuser'	=> '... but we are sure that he will type something, so be around.',
		'noposts2_ttl_withfriends'	=> 'It still does not have any posts from #USERNAME# and friends',
		'noposts2_txt_withfriends'	=> '... but we are sure that they will join, so be around.',
		'noposts_actions_ttl'	=> 'What do I have to do now ?',
		'noposts_actions_txt'	=> 'There is some things that you need to do to get<br />from all possibilities of '.SITE_TITLE,
		'noposts_actions_profile'	=> 'Fill out your profile with your personal information',
		'noposts_actions_avatar'	=> 'Browse your avatar',
		'noposts_actions_tags'		=> 'Type key word to your profile',
		'noposts_actions_search'	=> 'Search friends or people with the same interest as yours',
		'noposts_actions_invite'	=> 'If there are still not any know people in '.SITE_TITLE.', you can invite',
		'noposts_actions_post'	=> 'Type your first post now!',
		'noposts_actions_faq'	=> 'If you still need help, read here...',
		
		'noavatar_ttl'	=> 'You still do not have an <br />avatar ?',
		'noavatar_lnk'	=> 'upload',
		
		'viewpost_page_title'	=> 'Post review',
		'viewpost_page_linkprev'	=> 'previous',
		'viewpost_page_linknext'	=> 'last',
		
		'ignorebtn1'	=> 'Ignore',
		'ignorebtn1txt_'	=> 'If you ignore ##USERNAME##, you will not see his or her posts any more in '.SITE_TITLE.'.\n\nConfirm ignoring.',
		'ignorebtn1txt_m'	=> 'If you ignore ##USERNAME##, you will not see his posts in '.SITE_TITLE.'.\n\nConfirm ignoring.',
		'ignorebtn1txt_f'	=> 'If you ignore ##USERNAME##, you will not see her posts in '.SITE_TITLE.'.\n\nConfirm ignoring.',
		'ignorebtn2_'	=> 'Ignored',
		'ignorebtn2_m'	=> 'Ignored',
		'ignorebtn2_f'	=> 'Ignored',
		
		'MOBI_no_posts'	=> 'There are no posts',
		'MOBI_w_you'	=> 'direct',
		'MOBI_w_usr'	=> 'follow',
		'MOBI_w_usr2'	=> 'stop&nbsp;following',
		'MOBI_w_msg'	=> 'Message&nbsp;directly',
		'MOBI_onlyuser'	=> 'Only&nbsp;',
		'MOBI_withfr'	=> 'with&nbsp;friends',
		'MOBI_direct'	=> 'Direct&nbsp;messages',
		'MOBI_pr_about'	=> 'For&nbsp;',
		'MOBI_watch_ttl2_in_'	=> 'Follow&nbsp;him',
		'MOBI_watch_ttl2_in_m'	=> 'Follow&nbsp;him',
		'MOBI_watch_ttl2_in_f'	=> 'Follow&nbsp;her',
		'MOBI_watch_ttl2_out_'	=> 'He&nbsp;follows',
		'MOBI_watch_ttl2_out_m'	=> 'He&nbsp;follows',
		'MOBI_watch_ttl2_out_f'	=> 'She&nbsp;follows',
		'MOBI_pr_gender_m'	=> 'Men&nbsp;on&nbsp;',
		'MOBI_pr_gender_f'	=> 'Woman&nbsp;on&nbsp;',
		'MOBI_attached_link'	=> '(attached link)',
		'MOBI_attached_image'	=> '(attached picture)',
		'MOBI_attached_video'	=> '(attached videoclip)',
		'MOBI_attimage_ttl'	=> 'Picture review:',
		'MOBI_attimage_szs'	=> 'Sizes:',
		
		
		'guestbox_ttl'	=> 'Hello, this is the microblog of',
		'guestbox_txt'	=> 'use '.SITE_TITLE.', to share his or her everyday life with the world.',
		'guestbox_reg1'	=> 'Register',
		'guestbox_txt2'	=> ', to follow what he or she is doing and to read what he or she is posting.',
		'guestbox_reg2'	=> 'Join',
		'guestbox_or'	=> 'or',
		'guestbox_tour'	=> 'learn more for '.SITE_TITLE,
		
		'guest_vpk_title'		=> 'This post is a part of <a href="##USERLINK##">microblog of ##NAME##</a>.',
		'guest_vpk_text_'		=> 'He uses '.SITE_TITLE.', to communicate with his friends and to share his everyday life with them.',
		'guest_vpk_text_m'	=> 'He uses '.SITE_TITLE.', to communicate with friends and to share his everyday life with them.',
		'guest_vpk_text_f'	=> 'She uses '.SITE_TITLE.', to communicate with his friends and to share his everyday life with them.',
		
	);
	
?>
