<?php
             
              $lang              = array
              (
                            'edtprf_ttl_info'                            => 'Измените свой профиль',
                            'edtprf_ttl_avatar'              => 'Измените свой аватар',
                            'edtprf_ttl_tags'                            => 'Измените свои теги',
                            'edtprf_ttl_password'              => 'Измените свой пароль',
                            'edtprf_ttl_email'              => 'Измените свой е-мейл',
                            'edtprf_ttl_ignored'              => 'Проигнорированные пользователи',
                            'edtprf_ttl_notif'              => 'Уведомления по электронной почте',
                            'edtprf_ttl_feed'              => 'Лента постов',
                           
                            'prof_tab_info'                            => 'Информация',
                            'prof_tab_avatar'                            => 'Аватар',
                            'prof_tab_tags'                            => 'Теги',
                            'prof_tab_password'              => 'Пароль',
                            'prof_tab_email'                            => 'Е-мейл',
                            'prof_tab_ignored'              => 'Проигнорированные ',
                            'prof_tab_notif'                            => 'Уведомления',
                            'prof_tab_feed'                            => 'Фид',
                           
                            'profinfo_fullname'              => 'Полное имя',
                            'profinfo_fullname_dsc'              => 'Введите свое имя и фамилию',
                            'profinfo_website'              => 'Персональный Сайт',
                            'profinfo_website_dsc'              => 'Персональный сайт, блог или профиль',
                            'profinfo_website_err'              => 'Пожалуйста, дайте правильный адрес сайта',
                            'profinfo_city'                            => 'Местонахождение',
                            'profinfo_city_dsc'              => 'Страна или Город',
                            'profinfo_gender'                            => 'Пол',
                            'profinfo_gender_m'              => 'Мужчина',
                            'profinfo_gender_f'              => 'Женщина',
                            'profinfo_birthdt'              => 'Дата рождения',
                            'profinfo_birthdt_dsc'              => 'Формат: месяц-день-год',
                            'profinfo_aboutme'              => 'Напиши что-нибудь о себе',
                            'profinfo_aboutme_dsc'              => 'Краткое описание до 80 символов',
                            'profinfo_tags'                            => 'Personal tags',
                            'profinfo_tags_dsc'              => 'Личныe метки',
                            'profinfo_tags_dscr'              => 'Ваши личныe метки:<br />Опишите себя: поставьте до 10 меток.<br />Отделите их с запятой.',
                            'submitinfo_ok'              => 'Сохранить',
                            'submitinfo_ok1'              => 'Информация была успешно сохранена.',
                            'submitinfo_err'              => 'Ошибка',
                            'submitinfo_err1'              => 'Недействительный сайт',
                           
                            'profavat_noavat'              => 'Вы все ещё не имеете аватара!',
                            'profavat_add'              => 'Вы можете загрузить здесь',
                            'profavat_avat'              => 'Текущий аватар',
                            'profavat_add2'              => 'Заменить аватара',
                            'profavat_help'              => 'Допустимые форматы: GIF/JPEG/PNG.<br />Изображение должно быть больше чем на '.AVATAR_SIZE.'x'.AVATAR_SIZE.' пикселей.<br />Если форма не является квадратной, её части будут урезаны.',

                            'profavat_add_ok'                            => 'Готово',
                            'profavat_add_ok1'              => 'Аватар был успешно загружен',
                            'profavat_add_err'              => 'Ошибка',
                            'profavat_add_err1'              => 'Файл недействительный.',
                            'profavat_add_err2'              => 'Эта картинка слишком мала.',
                            'profavat_add_err3'              => 'Этот аватар не может быть скопирован.',
                           
                            'profmail_now'              => 'Текущий е-мейл',
                            'profmail_new'              => 'Новый е-мейл',
                            'profmail_new_2'              => 'Укажите ваш новый е-мейл',
                            'profmail_new2'              => 'Введи е-мейл снова',
                            'profmail_new2_2'              => 'Для подтверждения',
                            'profmail_pass'              => 'Ваш текущий пароль',
                            'profmail_pass_2'              => 'Для вашей защити',
                            'submitmail_ok'              => 'Готово',
                            'submitmail_ok1'              => 'Ваш е-мейл был изменен успешно.',
                            'submitmail_err'              => 'Ошибка',
                            'submitmail_err1'              => 'Неправильный е-мейл.',
                            'submitmail_err2'              => 'Этот е-майл адрес совпадает с текущим :)',
                            'submitmail_err3'              => 'Эти электронной почты не совпадают.',
                            'submitmail_err4'              => 'Существует еще один пользователь с таким же адресом электронной почты.',
                            'submitmail_err5'              => 'Пароль неправильный.',
                           
                            'profpass_now'              => 'Текущий пароль',
                            'profpass_now_2'              => 'Введите ваш текущий пароль',
                            'profpass_new'              => 'Новый пароль',
                            'profpass_new_2'              => 'Введите новый пароль',
                            'profpass_new2'              => 'Введите новый пароль ещё раз',
                            'profpass_new2_2'              => 'Для подтверждения',
                            'submitpass_ok'              => 'Готово',
                            'submitpass_ok1'              => 'Ваш пароль был изменен успешно.',
                            'submitpass_err'              => 'Готово',
                            'submitpass_err1'              => 'Пароль должен быть не менее 5 символов.',
                            'submitpass_err2'              => 'Эти пароли не совпадают.',
                            'submitpass_err3'              => 'Неправильный текущий пароль',
                           
                            'edit_submit'              => 'Сохранить',
                            'edit_submit2'              => 'Загрузить',
                           
                            'ignored_nores_ttl'              => 'Сдесь нет проигнорированных пользователей',
                            'ignored_nores_txt'              => 'Вы еще не проигнорировали никого.',
                            'ignored_delete_btn'              => 'удалить',
                            'ignored_del_confirm'              => 'Остановить игнорирование - вы уверены?',
                           
                            'notif_onwatch'              => 'Сообщайте мне каждый раз, когда кто-то начинает отслеживать за мной',
                            'notif_ondirect'              => 'Сообщайте мне каждый раз, когда кто-то отправляет мне прямое сообщение',
                            'notif_onmention'              => 'Сообщайте мне каждый раз, когда кто-то упоминает меня в своём посте',
                            'notif_periodic1'              => 'Сообщайте мне',
                            'notif_periodic2'              => 'Новости, касающиеся меня и моих друзей ',
                            'notif_periodd'              => 'один раз в день',
                            'notif_periodm'              => 'один раз в неделю',
                            'notif_ok_ttl'              => 'Готово',
                            'notif_ok_txt'              => 'Информация была успешно сохранена.',
                           
                            'proffeed_txt'              => 'RSS/Atom feed:',
                            'proffeed_ok'              => 'Готово',
                            'proffeed_err'              => 'Ошибка',
                            'proffeed_oktxt1'                            => 'Feed был добавлен успешно.',
                            'proffeed_oktxt2'                            => 'Feed был успешно удален.',
                            'proffeed_err_invalid'              => 'Этот feed не может быть прочитан правильно.',
                            'proffeed_submit1'              => 'Готово',
                            'proffeed_submit2'              => 'Изменение',
                           
              );
             
?>