<?php
             
              $lang              = array
              (
                            'subnav_onlyuser'                            => 'Только ',
                            'subnav_withfriends'              => 'Друзья`',
                            'subnav_onlyfav'                            => 'Избранные',
                            'subnav_onlydirect'              => 'Прямые Сообщения',
                           
                            'lefcol_edit_profile'              => 'Редактировать профиль',
                            'lefcol_watch_on_'                            => 'Отслеживать за ним',
                            'lefcol_watch_on_m'                            => 'Отслеживать за ним',
                            'lefcol_watch_on_f'                            => 'Отслеживать за ее',
                            'lefcol_watch_off'              => 'Перестать отслеживать',
                            'lefcol_watch_off_c'              => 'Перестать отслеживать – Вы уверены?',
                            'lefcol_post_direct'              => 'Прямое Сообщение',
                            'lefcol_get_rss'                            => 'RSS (РСС)',
                            'lefcol_invite'                            => 'Пригласить друзей',
                           
                            'lefcol_watch_u1'              => 'Следующий',
                            'lefcol_watch_u2'              => 'Отслежывающие',
                            'lefcol_watch_1_'                            => 'Отслеживать',
                            'lefcol_watch_1_m'              => 'Следующий',
                            'lefcol_watch_1_f'              => 'Следующий',
                            'lefcol_watch_2_'                            => 'Отслежывающие',
                            'lefcol_watch_2_m'              => 'Отслежывающие',
                            'lefcol_watch_2_f'              => 'Отслежывающие',
                           
                            'lefcol_user_gender_m'              => 'Мужчина',
                            'lefcol_user_gender_f'              => 'Женщина',
                            'lefcol_user_gender_m2'              => 'Мальчик',
                            'lefcol_user_gender_f2'              => 'Девушка',
                            'lefcol_user_age1'              => ',',
                            'lefcol_user_age2'              => ' год',
                           
                            'lefcol_tgs_ttl'                            => 'Теги',
                            'lefcol_tgs_ttl_mine'              => 'Теги',
                            'lefcol_tgs_ttl_add'              => 'добавить',
                            'lefcol_tgs_ttl_edt'              => 'редактировать',
                            'lefcol_tgs_none'                            => 'У вас нет никаких тагов',
                            'lefcol_tgs_users1'              => 'результат',
                            'lefcol_tgs_usersm'              => 'результат',
                           
                            'no_posts'              => 'Нет постов.',
                            'last_post'              => 'последний пост',
                           
                            'icon_fave'                            => 'добавить в Избранного',
                            'icon_unfave'              => 'Удалить из Избранного',
                            'icon_unfave_c'              => 'Удалить из Избранного – Вы уверены?',
                            'icon_del'                            => 'Удалить',
                            'icon_del_c'              => 'Удалить – Вы уверены?',
                            'icon_repl'                            => 'Посылать сообщение непосредственно',
                            'icon_permalink'              => 'Прямая ссылка на пост',
                           
                            'posttopicon_direct'              => 'Посылать сообщение непосредственно',
                            'posttopicon_mention'              => 'пост @',
                           
                            'noposts_ttl_onlyuser'              => 'Вы всё ещё ничего не опубликовали',
                            'noposts_txt_onlyuser'              => 'В этой закладке будут показаны ваши посты.Вы видите это здесь, нo лица, которые отслеживают за вами увидят их в закладке "Друзья". <a href="'.SITEURL.'faq">Дополнительная&nbsp;помощь&nbsp;&raquo;</a>',
                            'noposts_ttl_withfriends'              => 'У вас нет иикаких постов от ваших друзей',
                            'noposts_txt_withfriends'              => 'Ваши посты будут показаны здесь, наряду с постами пользователей, за каторыми вы <a href="'.SITEURL.'#USERNAME#/watched/type:in">отслеживаете</a>. Вы можете нажать кнопку <a href="'.SITEURL.'search">search</a> , чтобы найти друзей или же вы можете <a href="'.SITEURL.'invite">отправить&nbsp;приглашения</a>. <a href="'.SITEURL.'faq">Дополнительная&nbsp;помощь&nbsp;&raquo;</a>',
                            'noposts_ttl_ifmentioned'              => 'Никто не упомянул вас',
                            'noposts_txt_ifmentioned'              => 'Здесь посты, в которых кто-то упомянул вас. <a href="'.SITEURL.'faq">Another&nbsp;help&nbsp;&raquo;</a>',
                            'noposts_ttl_onlyfav'              => 'У вас нет любимых постов',
                            'noposts_txt_onlyfav'              => 'Посты которые вы отметите как "избранное", будут размещены здесь. Для сохранения постов и других вещей, которые вам нравятся, нажмите на звездочку в постах. <a href="'.SITEURL.'faq">Дополнительная&nbsp;помощь&nbsp;&raquo;</a>',
                            'noposts_ttl_onlydirect'              => 'У вас нет никаких непосредственных сообщений',
                            'noposts_txt_onlydirect'              => 'личные сообщения между вами и другими пользователями на '.SITE_TITLE.'. Чтобы отправить личное сообщение для кого-то, войдите в свой профиль и нажмите на кнопку "Посылать сообщение&nbsp;непосредственно". <a href="'.SITEURL.'faq">Дополнительная&nbsp;помощь&nbsp;&raquo;</a>',
                            'noposts2_ttl_onlyuser'              => 'У вас всё ещё не имеют каких-либо сообщений от #USERNAME#',
                            'noposts2_txt_onlyuser'              => '... но мы уверены, что это скоро произойдёт, так что будте рйадом.',
                            'noposts2_ttl_withfriends'              => 'У вас всё ещё не имеют каких-либо постов от #USERNAME# и от ваших друзей',
                            'noposts2_txt_withfriends'              => '... но мы уверены, что они вскоре присоединятся, так что будте рыадом.',
                            'noposts_actions_ttl'              => 'Что мне делать сейчас?',
                            'noposts_actions_txt'              => 'Существует несколько вещей, которые нужно сделать для того, чтобы получить<br />все возможности от  '.SITE_TITLE,
                            'noposts_actions_profile'              => 'Заполните свой профиль с личной информацией',
                            'noposts_actions_avatar'              => 'Проглядывайте ваш аватор',
                            'noposts_actions_tags'                            => 'Введите ключевые слова для вашего профиля',
                            'noposts_actions_search'              => 'Искать друзей или людей с одинаковыми интересами',
                            'noposts_actions_invite'              => 'Если на сайте '.SITE_TITLE.', всё ещё нет знакомых людей, вы можете их пригласить',
                            'noposts_actions_post'              => 'Введите ваш первы пост прямо сейчас!',
                            'noposts_actions_faq'              => 'Если вы по-прежнему нуждаются в помощи, читайте здесь...',
                           
                            'noavatar_ttl'              => 'У вас всё ещё нет <br />аватора?',
                            'noavatar_lnk'              => 'загружать',
                           
                            'viewpost_page_title'              => 'Пост рецензия',
                            'viewpost_page_linkprev'              => 'предыдущий',
                            'viewpost_page_linknext'              => 'последний',
                           
                            'ignorebtn1'              => 'Игнорировать',
                            'ignorebtn1txt_'              => 'Если вы игнорируете ##USERNAME##, вы больше не увидите на сайте его или её посты '.SITE_TITLE.'.\n\nConfirm ignoring.',
                            'ignorebtn1txt_m'              => 'Если вы игнорируете ##USERNAME##, вы не будите видеть на саите его посты '.SITE_TITLE.'.\n\nConfirm ignoring.',
                            'ignorebtn1txt_f'              => 'Если вы игнорируете ##USERNAME##, вы не будите видеть на саите её посты '.SITE_TITLE.'.\n\nConfirm ignoring.',
                            'ignorebtn2_'              => 'Проигнорирован(а)',
                            'ignorebtn2_m'              => 'Проигнорирован',
                            'ignorebtn2_f'              => 'Проигнорирована',
                           
                            'MOBI_no_posts'              => 'Нет постов',
                            'MOBI_w_you'              => 'прямоы',
                            'MOBI_w_usr'              => 'отслеживать',
                            'MOBI_w_usr2'              => 'перестать&nbsp;отслеживать',
                            'MOBI_w_msg'              => 'Посылать сообщение&nbsp;непосредственно',
                            'MOBI_onlyuser'              => 'Только&nbsp;',
                            'MOBI_withfr'              => 'с&nbsp;друзьями',
                            'MOBI_direct'              => 'Непосредственные&nbsp;сообщения',
                            'MOBI_pr_about'              => 'Для&nbsp;',
                            'MOBI_watch_ttl2_in_'              => 'Отслеживайте за&nbsp;ним',
                            'MOBI_watch_ttl2_in_m'              => 'Отслеживайте за&nbsp;ним',
                            'MOBI_watch_ttl2_in_f'              => 'Отслеживайте за&nbsp;ней',
                            'MOBI_watch_ttl2_out_'              => 'Следующий',
                            'MOBI_watch_ttl2_out_m'              => 'Следующий',
                            'MOBI_watch_ttl2_out_f'              => 'Следующий',
                            'MOBI_pr_gender_m'              => 'Мужчина&nbsp;on&nbsp;',
                            'MOBI_pr_gender_f'              => 'Женщина&nbsp;on&nbsp;',
                            'MOBI_attached_link'              => '(прикрепленная ссылка)',
                            'MOBI_attached_image'              => '(прикреплённая фотография)',
                            'MOBI_attached_video'              => '(прикрепленное видео)',
                            'MOBI_attimage_ttl'              => 'Обзор фотографий:',
                            'MOBI_attimage_szs'              => 'Размеры:',
                           
                           
                            'guestbox_ttl'              => 'Здравствуйте, это микроблог от',
                            'guestbox_txt'              => 'использовать '.SITE_TITLE.', делитсья своей каждодневной жизнью с миром.',
                            'guestbox_reg1'              => 'Зарегистрируйтесь',
                            'guestbox_txt2'              => ', чтобы следить, что он или она делает, и прочитать о том, что он или она обьявляет.',
                            'guestbox_reg2'              => 'Присоединяйтесь',
                            'guestbox_or'              => 'или',
                            'guestbox_tour'              => 'узнать больше '.SITE_TITLE,
                           
                            'guest_vpk_title'                            => 'Этот пост является частью  <a href="##USERLINK##">microblogа ##NAME##</a>.',
                            'guest_vpk_text_'                            => 'Он использует '.SITE_TITLE.', чтоб общаться со своими друзьями и делиться с ними своей повседневной жизнью.',
                            'guest_vpk_text_m'              => 'Он использует '.SITE_TITLE.', чтоб общаться со своими друзьями и делиться с ними своей повседневной жизнью.',
                            'guest_vpk_text_f'              => 'Она использует '.SITE_TITLE.', чтоб общаться со своими друзьями и делиться с ними своей повседневной жизнью.',
                           
              );
?>