<?php
	
	$lang	= array
	(
		'subnav_onlyuser'		=> '',
		'subnav_withfriends'	=> '好友',
		'subnav_onlyfav'		=> '收藏',
		'subnav_onlydirect'	=> '私人消息',
		
		'lefcol_edit_profile'	=> '我的配置',
		'lefcol_watch_on_'		=> '关注TA',
		'lefcol_watch_on_m'		=> '关注他',
		'lefcol_watch_on_f'		=> '关注她',
		'lefcol_watch_off'	=> '停止关注此人',
		'lefcol_watch_off_c'	=> '停止关注该用户，确定？',
		'lefcol_post_direct'	=> '发送私人消息',
		'lefcol_get_rss'		=> 'RSS更新订阅',
		'lefcol_invite'		=> '邀请朋友',
		
		'lefcol_watch_u1'	=> '我关注的人',
		'lefcol_watch_u2'	=> '关注我的人',
		'lefcol_watch_1_'		=> 'TA关注的人',
		'lefcol_watch_1_m'	=> '他关注的人',
		'lefcol_watch_1_f'	=> '她关注的人',
		'lefcol_watch_2_'		=> '关注TA的人',
		'lefcol_watch_2_m'	=> '关注他的人',
		'lefcol_watch_2_f'	=> '关注她的人',
		
		'lefcol_user_gender_m'	=> '男士',
		'lefcol_user_gender_f'	=> '女士',
		'lefcol_user_gender_m2'	=> '男孩',
		'lefcol_user_gender_f2'	=> '女孩',
		'lefcol_user_age1'	=> '，',
		'lefcol_user_age2'	=> '岁',
		
		'lefcol_tgs_ttl'		=> '关键词',
		'lefcol_tgs_ttl_mine'	=> '关键词',
		'lefcol_tgs_ttl_add'	=> '添加',
		'lefcol_tgs_ttl_edt'	=> '编辑',
		'lefcol_tgs_none'		=> '还未添加关键词。',
		'lefcol_tgs_users1'	=> '结果',
		'lefcol_tgs_usersm'	=> '结果',
		
		'no_posts'	=> '该用户还没未发布任何帖子。',
		'last_post'	=> '最新发布',
		
		'icon_fave'		=> '添加到收藏',
		'icon_unfave'	=> '从收藏中删除',
		'icon_unfave_c'	=> '确认从收藏中删除？',
		'icon_del'		=> '删除',
		'icon_del_c'	=> '确认删除？',
		'icon_repl'		=> '回复',
		'icon_permalink'	=> '本帖链接',
		
		'posttopicon_direct'	=> '发送私人消息',
		'posttopicon_mention'	=> '回复@',
		
		'noposts_ttl_onlyuser'	=> '您还没未发布任何帖子。',
		'noposts_txt_onlyuser'	=> '您的帖子将会显示在此页面。关注您的人将会在TA的“好友”页面看到您的帖子。 <a href="'.SITEURL.'faq">更多帮助</a>',
		'noposts_ttl_withfriends'	=> '您的好友们还未发布任何帖子。',
		'noposts_txt_withfriends'	=> '您的帖子和您<a href="'.SITEURL.'#USERNAME#/watched/type:in">关注的人</a>的帖子将会同时出现在这里。您可以通过<a href="'.SITEURL.'search">搜索</a>或者<a href="'.SITEURL.'invite">发送邀请</a>与更多人成为好友。 <a href="'.SITEURL.'faq">更多帮助</a>',
		'noposts_ttl_ifmentioned'	=> '还没人在帖子中提及您',
		'noposts_txt_ifmentioned'	=> '这里显示了来自所有用户中提及您的帖子。<a href="'.SITEURL.'faq">更多帮助</a>',
		'noposts_ttl_onlyfav'	=> '您还未收藏任何帖子',
		'noposts_txt_onlyfav'	=> '您标记为“收藏”的帖子将显示在这里。点击每个帖子下的五角星符号可以收藏该帖。<a href="'.SITEURL.'faq">更多帮助</a>',
		'noposts_ttl_onlydirect'	=> '您还没有收到过私人消息',
		'noposts_txt_onlydirect'	=> '『'.SITE_TITLE.'』用户之间发送的私人消息。点击好友头像下的“私人消息”按钮即可向TA发送私人消息。<a href="'.SITEURL.'faq">更多帮助</a>',
		'noposts2_ttl_onlyuser'	=> '#USERNAME#尚未发布任何帖子',
		'noposts2_txt_onlyuser'	=> '……但是我们确信TA一定会开口说话。记得回来看看。',
		'noposts2_ttl_withfriends'	=> '#USERNAME#和TA的好友尚未发布任何帖子',
		'noposts2_txt_withfriends'	=> '……但是我们确信他们一定会滔滔不绝。记得回来看看。',
		'noposts_actions_ttl'	=> '现在该做点什么呢？',
		'noposts_actions_txt'	=> '看看『'.SITE_TITLE.'』还带来了什么惊喜。不要迟疑，尝试一下！',
		'noposts_actions_profile'	=> '完善个人资料',
		'noposts_actions_avatar'	=> '设置头像',
		'noposts_actions_tags'		=> '为个人资料添加关键词（他人将会更容易地发现您）',
		'noposts_actions_search'	=> '寻找和您臭味相投的朋友',
		'noposts_actions_invite'	=> '如果他们还未加入『'.SITE_TITLE.'』，向他们发送邀请',
		'noposts_actions_post'	=> '发布第一篇帖子',
		'noposts_actions_faq'	=> '如果您仍然觉得很迷惑，请阅读这里',
		
		'noavatar_ttl'	=> '还没有头像吗？',
		'noavatar_lnk'	=> '上传',
		
		'viewpost_page_title'	=> '预览',
		'viewpost_page_linkprev'	=> '上一项',
		'viewpost_page_linknext'	=> '下一项',
		
		'ignorebtn1'	=> '忽略该用户',
		'ignorebtn1txt_'	=> '忽略##USERNAME##将使您无法在『'.SITE_TITLE.'』中看到TA的任何帖子和消息。\n\n确认？',
		'ignorebtn1txt_m'	=> '忽略##USERNAME##将使您无法在『'.SITE_TITLE.'』中看到他的任何帖子和消息。\n\n确认？',
		'ignorebtn1txt_f'	=> '忽略##USERNAME##将使您无法在『'.SITE_TITLE.'』中看到她的任何帖子和消息。\n\n确认？',
		'ignorebtn2_'	=> '已忽略',
		'ignorebtn2_m'	=> '已忽略',
		'ignorebtn2_f'	=> '已忽略',
		
		'MOBI_no_posts'	=> '还未发表任何帖子',
		'MOBI_w_you'	=> '私人消息',
		'MOBI_w_usr'	=> '开始关注此人',
		'MOBI_w_usr2'	=> '停止关注此人',
		'MOBI_w_msg'	=> '发送私人消息',
		'MOBI_onlyuser'	=> '',
		'MOBI_withfr'	=> '好友',
		'MOBI_direct'	=> '私人消息',
		'MOBI_pr_about'	=> '',
		'MOBI_watch_ttl2_in_'	=> '关注TA的人',
		'MOBI_watch_ttl2_in_m'	=> '关注他的人',
		'MOBI_watch_ttl2_in_f'	=> '关注她的人',
		'MOBI_watch_ttl2_out_'	=> 'TA关注的人',
		'MOBI_watch_ttl2_out_m'	=> '他关注的人',
		'MOBI_watch_ttl2_out_f'	=> '她关注的人',
		'MOBI_pr_gender_m'	=> '男性',
		'MOBI_pr_gender_f'	=> '女性',
		'MOBI_attached_link'	=> '（包含链接）',
		'MOBI_attached_image'	=> '（包含图片）',
		'MOBI_attached_video'	=> '（包含视频）',
		'MOBI_attimage_ttl'	=> '图片预览',
		'MOBI_attimage_szs'	=> '图片大小',
		
		
		'guestbox_ttl'	=> '您好，这是一个微型博客',
		'guestbox_txt'	=> '正在这里分享TA的点点滴滴。',
		'guestbox_reg1'	=> '加入我们',
		'guestbox_txt2'	=> '就能和朋友们分享快乐。',
		'guestbox_reg2'	=> '开始'.SITE_TITLE,
		'guestbox_or'	=> '或者',
		'guestbox_tour'	=> '看看再说',
		
		'guest_vpk_title'		=> '本贴由<a href="##USERLINK##">##NAME##</a>发布。',
		'guest_vpk_text_'		=> 'TA正在使用『'.SITE_TITLE.'』与朋友交流并且展示自己的所思所想。',
		'guest_vpk_text_m'	=> '他正在使用『'.SITE_TITLE.'』与朋友交流并且展示自己的所思所想。',
		'guest_vpk_text_f'	=> '她正在使用『'.SITE_TITLE.'』与朋友交流并且展示自己的所思所想。',
		
	);
	
?>
